/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ResetPasswordMessageRouteImport } from './routes/reset-password.message'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthenticatedAdminOrganizationIndexRouteImport } from './routes/_authenticated/admin/organization.index'
import { Route as AuthenticatedAdminEmailsIndexRouteImport } from './routes/_authenticated/admin/emails.index'
import { Route as AuthenticatedAdminEmailsEmailIdRouteImport } from './routes/_authenticated/admin/emails.$emailId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ResetPasswordMessageRoute = ResetPasswordMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOrganizationIndexRoute =
  AuthenticatedAdminOrganizationIndexRouteImport.update({
    id: '/admin/organization/',
    path: '/admin/organization/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEmailsIndexRoute =
  AuthenticatedAdminEmailsIndexRouteImport.update({
    id: '/admin/emails/',
    path: '/admin/emails/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEmailsEmailIdRoute =
  AuthenticatedAdminEmailsEmailIdRouteImport.update({
    id: '/admin/emails/$emailId',
    path: '/admin/emails/$emailId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/emails/$emailId': typeof AuthenticatedAdminEmailsEmailIdRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsIndexRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/emails/$emailId': typeof AuthenticatedAdminEmailsEmailIdRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsIndexRoute
  '/admin/organization': typeof AuthenticatedAdminOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/emails/$emailId': typeof AuthenticatedAdminEmailsEmailIdRoute
  '/_authenticated/admin/emails/': typeof AuthenticatedAdminEmailsIndexRoute
  '/_authenticated/admin/organization/': typeof AuthenticatedAdminOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/'
    | '/api/auth/$'
    | '/admin'
    | '/admin/emails/$emailId'
    | '/admin/emails'
    | '/admin/organization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/'
    | '/api/auth/$'
    | '/admin'
    | '/admin/emails/$emailId'
    | '/admin/emails'
    | '/admin/organization'
  id:
    | '__root__'
    | '/_authenticated'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/_authenticated/'
    | '/api/auth/$'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/emails/$emailId'
    | '/_authenticated/admin/emails/'
    | '/_authenticated/admin/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/reset-password/message': {
      id: '/reset-password/message'
      path: '/message'
      fullPath: '/reset-password/message'
      preLoaderRoute: typeof ResetPasswordMessageRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/organization/': {
      id: '/_authenticated/admin/organization/'
      path: '/admin/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/emails/': {
      id: '/_authenticated/admin/emails/'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/emails/$emailId': {
      id: '/_authenticated/admin/emails/$emailId'
      path: '/admin/emails/$emailId'
      fullPath: '/admin/emails/$emailId'
      preLoaderRoute: typeof AuthenticatedAdminEmailsEmailIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmailsEmailIdRoute: typeof AuthenticatedAdminEmailsEmailIdRoute
  AuthenticatedAdminEmailsIndexRoute: typeof AuthenticatedAdminEmailsIndexRoute
  AuthenticatedAdminOrganizationIndexRoute: typeof AuthenticatedAdminOrganizationIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEmailsEmailIdRoute: AuthenticatedAdminEmailsEmailIdRoute,
  AuthenticatedAdminEmailsIndexRoute: AuthenticatedAdminEmailsIndexRoute,
  AuthenticatedAdminOrganizationIndexRoute:
    AuthenticatedAdminOrganizationIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ResetPasswordRouteChildren {
  ResetPasswordMessageRoute: typeof ResetPasswordMessageRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordMessageRoute: ResetPasswordMessageRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
