/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ResetPasswordMessageRouteImport } from './routes/reset-password.message'
import { Route as AdminEmailsIndexRouteImport } from './routes/admin/emails.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminEmailsEmailIdRouteImport } from './routes/admin/emails.$emailId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordMessageRoute = ResetPasswordMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const AdminEmailsIndexRoute = AdminEmailsIndexRouteImport.update({
  id: '/admin/emails/',
  path: '/admin/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsEmailIdRoute = AdminEmailsEmailIdRouteImport.update({
  id: '/admin/emails/$emailId',
  path: '/admin/emails/$emailId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/admin': typeof AdminIndexRoute
  '/admin/emails/$emailId': typeof AdminEmailsEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/admin': typeof AdminIndexRoute
  '/admin/emails/$emailId': typeof AdminEmailsEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/reset-password/message': typeof ResetPasswordMessageRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/emails/$emailId': typeof AdminEmailsEmailIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/admin'
    | '/admin/emails/$emailId'
    | '/api/auth/$'
    | '/admin/emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/admin'
    | '/admin/emails/$emailId'
    | '/api/auth/$'
    | '/admin/emails'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/reset-password/message'
    | '/admin/'
    | '/admin/emails/$emailId'
    | '/api/auth/$'
    | '/admin/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmailsEmailIdRoute: typeof AdminEmailsEmailIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AdminEmailsIndexRoute: typeof AdminEmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/message': {
      id: '/reset-password/message'
      path: '/message'
      fullPath: '/reset-password/message'
      preLoaderRoute: typeof ResetPasswordMessageRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/admin/emails/': {
      id: '/admin/emails/'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails/$emailId': {
      id: '/admin/emails/$emailId'
      path: '/admin/emails/$emailId'
      fullPath: '/admin/emails/$emailId'
      preLoaderRoute: typeof AdminEmailsEmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResetPasswordRouteChildren {
  ResetPasswordMessageRoute: typeof ResetPasswordMessageRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordMessageRoute: ResetPasswordMessageRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmailsEmailIdRoute: AdminEmailsEmailIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AdminEmailsIndexRoute: AdminEmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
